package de.hglabor.loot

import org.bukkit.Material

enum class LootSet(val materials: HashMap<Material, String>, iconMaterial: Material) {

    OVERWORLD(
        hashMapOf(
            Pair(Material.ACACIA_DOOR, ""),
            Pair(Material.ACTIVATOR_RAIL, ""),
            Pair(Material.ANDESITE, ""),
            Pair(Material.ARMOR_STAND, ""),
            Pair(Material.ANVIL, ""),
            Pair(Material.ARROW, ""),
            Pair(Material.BAKED_POTATO, ""),
            Pair(Material.BARREL, ""),
            Pair(Material.BARREL, ""),
            Pair(Material.BEEHIVE, ""),
            Pair(Material.BEETROOT_SOUP, ""),
            Pair(Material.BELL, ""),
            Pair(Material.BIRCH_BOAT, ""),
            Pair(Material.BLACK_CONCRETE, ""),
            Pair(Material.BLAST_FURNACE, ""),
            Pair(Material.BLUE_CONCRETE_POWDER, ""),
            Pair(Material.BONE_BLOCK, ""),
            Pair(Material.BOOKSHELF, ""),
            Pair(Material.BOW, ""),
            Pair(Material.BREWING_STAND, ""),
            Pair(Material.BRICK, ""),
            Pair(Material.BRICKS, ""),
            Pair(Material.BUCKET, ""),
            Pair(Material.CAKE, ""),
            Pair(Material.CAMPFIRE, ""),
            Pair(Material.CARROT_ON_A_STICK, ""),
            Pair(Material.CARTOGRAPHY_TABLE, ""),
            Pair(Material.CAULDRON, ""),
            Pair(Material.CHAIN, ""),
            Pair(Material.CHARCOAL, ""),
            Pair(Material.CHEST_MINECART, ""),
            Pair(Material.CHISELED_SANDSTONE, ""),
            Pair(Material.CLAY_BALL, ""),
            Pair(Material.COARSE_DIRT, ""),
            Pair(Material.COARSE_DIRT, ""),
            Pair(Material.CORNFLOWER, ""),
            Pair(Material.CYAN_CONCRETE_POWDER, ""),
            Pair(Material.CYAN_GLAZED_TERRACOTTA, ""),
            Pair(Material.DIAMOND, ""),
            Pair(Material.DIAMOND_CHESTPLATE, ""),
            Pair(Material.DIAMOND_HOE, ""),
            Pair(Material.DIAMOND_PICKAXE, ""),
            Pair(Material.DISPENSER, ""),
            Pair(Material.DRIED_KELP_BLOCK, ""),
            Pair(Material.EMERALD, ""),
            Pair(Material.ENCHANTED_BOOK, ""),
            Pair(Material.ENCHANTING_TABLE, ""),
            Pair(Material.ENDER_PEARL, ""),
            Pair(Material.FERMENTED_SPIDER_EYE, ""),
            Pair(Material.FIRE_CHARGE, ""),
            Pair(Material.FIREWORK_ROCKET, ""),
            Pair(Material.FIREWORK_STAR, "extra/firework_star"),
            Pair(Material.FISHING_ROD, ""),
            Pair(Material.FLETCHING_TABLE, ""),
            Pair(Material.FLINT_AND_STEEL, ""),
            Pair(Material.FLOWER_POT, ""),
            Pair(Material.FURNACE_MINECART, ""),
            Pair(Material.GLASS_BOTTLE, ""),
            Pair(Material.GLISTERING_MELON_SLICE, ""),
            Pair(Material.GOLD_BLOCK, ""),
            Pair(Material.GOLD_INGOT, ""),
            Pair(Material.GOLDEN_APPLE, ""),
            Pair(Material.GOLDEN_BOOTS, ""),
            Pair(Material.GOLDEN_CARROT, ""),
            Pair(Material.HAY_BLOCK, ""),
            Pair(Material.HONEY_BOTTLE, ""),
            Pair(Material.HOPPER, ""),
            Pair(Material.INK_SAC, ""),
            Pair(Material.IRON_AXE, ""),
            Pair(Material.IRON_BARS, ""),
            Pair(Material.IRON_BLOCK, ""),
            Pair(Material.IRON_DOOR, ""),
            Pair(Material.IRON_HORSE_ARMOR, ""),
            Pair(Material.JACK_O_LANTERN, ""),
            Pair(Material.JUNGLE_DOOR, ""),
            Pair(Material.KELP, ""),
            Pair(Material.LADDER, ""),
            Pair(Material.LAPIS_LAZULI, ""),
            Pair(Material.LAVA_BUCKET, ""),
            Pair(Material.LEATHER, ""),
            Pair(Material.LEVER, ""),
            Pair(Material.LILY_PAD, ""),
            Pair(Material.MILK_BUCKET, ""),
            Pair(Material.MINECART, ""),
            Pair(Material.NOTE_BLOCK, ""),
            Pair(Material.OAK_BOAT, ""),
            Pair(Material.OAK_LEAVES, ""),
            Pair(Material.PAINTING, ""),
            Pair(Material.PAPER, ""),
            Pair(Material.POTION, ""),
            Pair(Material.POWERED_RAIL, ""),
            Pair(Material.PUFFERFISH_BUCKET, ""),
            Pair(Material.PUMPKIN_PIE, ""),
            Pair(Material.RAIL, ""),
            Pair(Material.ROTTEN_FLESH, ""),
            Pair(Material.SADDLE, ""),
            Pair(Material.SAND, ""),
            Pair(Material.SANDSTONE, ""),
            Pair(Material.SCUTE, ""),
            Pair(Material.SEA_PICKLE, ""),
            Pair(Material.SHEARS, ""),
            Pair(Material.SLIME_BALL, ""),
            Pair(Material.SMITHING_TABLE, ""),
            Pair(Material.SMOOTH_STONE, ""),
            Pair(Material.SNOWBALL, ""),
            Pair(Material.SPECTRAL_ARROW, ""),
            Pair(Material.STICK, ""),
            Pair(Material.STONE_AXE, ""),
            Pair(Material.STONE_PICKAXE, ""),
            Pair(Material.STONE_SHOVEL, ""),
            Pair(Material.STRING, ""),
            Pair(Material.SUGAR, ""),
            Pair(Material.TNT_MINECART, ""),
            Pair(Material.TORCH, ""),
            Pair(Material.TRIDENT, ""),
            Pair(Material.TURTLE_HELMET, ""),
            Pair(Material.WHEAT, ""),
            Pair(Material.WHEAT_SEEDS, ""),
            Pair(Material.WOODEN_AXE, ""),
            Pair(Material.WOODEN_SWORD, ""),
            Pair(Material.WRITABLE_BOOK, "")
        ), Material.GRASS_BLOCK
    ),
    NETHER(
        hashMapOf(
            Pair(Material.ANCIENT_DEBRIS, ""),
            Pair(Material.BASALT, ""),
            Pair(Material.BLAZE_POWDER, ""),
            Pair(Material.BLAZE_ROD, ""),
            Pair(Material.BLAZE_ROD, ""),
            Pair(Material.CHISELED_NETHER_BRICKS, ""),
            Pair(Material.CHISELED_QUARTZ_BLOCK, ""),
            Pair(Material.CRIMSON_DOOR, ""),
            Pair(Material.GHAST_TEAR, ""),
            Pair(Material.GILDED_BLACKSTONE, ""),
            Pair(Material.NETHER_BRICKS, ""),
            Pair(Material.NETHER_GOLD_ORE, ""),
            Pair(Material.NETHER_QUARTZ_ORE, ""),
            Pair(Material.NETHER_STAR, ""),
            Pair(Material.NETHER_WART, ""),
            Pair(Material.NETHERITE_BOOTS, ""),
            Pair(Material.NETHERITE_SCRAP, ""),
            Pair(Material.NETHERRACK, ""),
            Pair(Material.QUARTZ, ""),
            Pair(Material.QUARTZ_BRICKS, ""),
            Pair(Material.RESPAWN_ANCHOR, ""),
            Pair(Material.SHROOMLIGHT, ""),
            Pair(Material.SOUL_CAMPFIRE, ""),
            Pair(Material.SOUL_SOIL, ""),
            Pair(Material.SOUL_TORCH, ""),
            Pair(Material.GLOWSTONE, ""),
            Pair(Material.ENDER_EYE, ""),
            Pair(Material.END_CRYSTAL, "")
        ), Material.NETHERRACK
    ),
    WATER(
        hashMapOf(
            Pair(Material.PRISMARINE, ""),
            Pair(Material.HEART_OF_THE_SEA, ""),
            Pair(Material.SPONGE, ""),
            Pair(Material.WET_SPONGE, ""),
        ), Material.WATER_BUCKET
    ),
    TURTLE(
        hashMapOf(
            Pair(Material.TRIDENT, ""),
            Pair(Material.TURTLE_HELMET, ""),
            Pair(Material.SCUTE, ""),
        ), Material.SCUTE
    );

    var isEnabled = true


}